$schema: http://json-schema.org/schema#
description: configuration-data, which represents the structure of the config-file.
definitions: 

    USNConfig:
        description: the definition of the config-file.
        type: object
        properties:
            eth:
                description: ethereum- connection 
                type: object
                additionalProperties: false
                properties:
                    clients:
                        description: the urls of the available clients. Each url must be either a http(s), ws-url or a ipc-path
                        minItems: 1
                        type: array
                        example: ['http://myremote-client:8545', 'ws://mylocalclient:84','myipc-path']
                        items:
                            type: string
            contracts:
                description: a list of base-contracts
                type: object
                additionalProperties: false
                properties: 
                    profiles: 
                        description: a simple map holding public profiles for addresses [ProfileRegistry.sol](https://github.com/slockit/usn-lib/tree/develop/contracts/profiles)
                        type: string
                        format: address
                    registry:
                        description: the [USN-Resolver](https://github.com/slockit/usn-lib/blob/develop/contracts/ENS/USNResolver.sol)
                        type: string
                        format: address
                    usnRegistrar:
                        description: the [USN-Registrar](https://github.com/slockit/usn-lib/blob/develop/contracts/ENS/USNRegistrar.sol), used to register new ENS-Domains 
                        type: string
                        format: address
                    stateManager:
                        description: the [StatechannelManager](https://github.com/slockit/usn-lib/tree/develop/contracts/states)
                        type: string
                        format: address
            services:
                description: the Services of the USN
                type: object
                additionalProperties: false
                properties:
                    stateServer:
                        description: url of the statechannel manager
                        type: string
                        format: uri
                        example: https://state-server-test.usn.slock.it
                    hub:
                        description: url of the message hub
                        type: string
                        format: uri
                        example: https://hub-test-usn.slock.it
                    search:
                        description: url of the search-service
                        type: string
                        format: uri
                        example: https://search-test-usn.slock.it
            configDir:
                description: the directory where to store all config-files.
                type: string
                example: /etc/usn
            logger:
                type: object
                description: loggin-configuration
                additionalProperties: false
                properties:
                    colors:
                        description: use colors in logfiles
                        type: boolean
                        example: true
                    append:
                        description: append logfile
                        type: boolean
                        example: false
                    level:
                        description: Loglevel 
                        type: string
                        enum: 
                            - debug
                            - info
                            - warn
                            - error
                            - verbose
                            - silly
                    file:
                        description: path to the logfile
                        type: string
                        example: usn.log
                    logRPC:
                        description: if true, all JSON-RPC-requests will be logged in the logfile in order to debug
                        type: boolean
                        example: false

